"""
services/notification.py — Notification Layer.

Sends an HTML email alert for every "High" or "Critical" severity event.
Uses aiosmtplib for non-blocking async delivery so it never stalls the
main request/response cycle.

The email includes:
  • Severity badge (colour-coded)
  • MITRE ATT&CK technique ID and name
  • IOC reputation verdict
  • Raw event metadata
"""
import logging
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText

import aiosmtplib

from config import (
    ALERT_RECIPIENTS,
    SMTP_HOST,
    SMTP_PASSWORD,
    SMTP_PORT,
    SMTP_USER,
)
from models.alert import Alert

logger = logging.getLogger(__name__)

# Severities that warrant an email notification
NOTIFY_SEVERITIES = {"High", "Critical"}

# Colour map for severity badge in HTML email
SEVERITY_COLOURS: dict[str, str] = {
    "Low":      "#28a745",   # green
    "Medium":   "#ffc107",   # amber
    "High":     "#fd7e14",   # orange
    "Critical": "#dc3545",   # red
}


def _build_html_body(alert: Alert) -> str:
    colour = SEVERITY_COLOURS.get(alert.severity, "#6c757d")
    ioc_verdict = (
        f"<span style='color:red;font-weight:bold;'>⚠ {alert.ioc_reputation} "
        f"({alert.ioc_provider})</span>"
        if alert.ioc_malicious
        else f"<span style='color:green;'>✔ {alert.ioc_reputation or 'N/A'} "
             f"({alert.ioc_provider or 'N/A'})</span>"
    )

    return f"""
<!DOCTYPE html>
<html>
<body style="font-family:Arial,sans-serif;background:#f4f4f4;padding:20px;">
  <div style="max-width:680px;margin:auto;background:#fff;border-radius:8px;
              border-top:5px solid {colour};padding:30px;">

    <h2 style="color:#333;">
      🚨 SIEM Alert —
      <span style="background:{colour};color:#fff;padding:3px 12px;
                   border-radius:12px;font-size:14px;">{alert.severity}</span>
    </h2>

    <table style="width:100%;border-collapse:collapse;font-size:14px;">
      <tr style="background:#f8f8f8;">
        <td style="padding:8px;font-weight:bold;width:35%;">Alert ID</td>
        <td style="padding:8px;">{alert.id}</td>
      </tr>
      <tr>
        <td style="padding:8px;font-weight:bold;">Event Type</td>
        <td style="padding:8px;">{alert.event_type}</td>
      </tr>
      <tr style="background:#f8f8f8;">
        <td style="padding:8px;font-weight:bold;">Source IP</td>
        <td style="padding:8px;font-family:monospace;">{alert.source_ip}</td>
      </tr>
      <tr>
        <td style="padding:8px;font-weight:bold;">Timestamp</td>
        <td style="padding:8px;">{alert.timestamp}</td>
      </tr>
      <tr style="background:#f8f8f8;">
        <td style="padding:8px;font-weight:bold;">Description</td>
        <td style="padding:8px;">{alert.description}</td>
      </tr>
    </table>

    <h3 style="color:#555;margin-top:24px;">🎯 MITRE ATT&CK</h3>
    <table style="width:100%;border-collapse:collapse;font-size:14px;">
      <tr style="background:#f8f8f8;">
        <td style="padding:8px;font-weight:bold;width:35%;">Technique ID</td>
        <td style="padding:8px;font-family:monospace;">
          {alert.mitre_technique_id or "N/A"}
        </td>
      </tr>
      <tr>
        <td style="padding:8px;font-weight:bold;">Technique Name</td>
        <td style="padding:8px;">{alert.mitre_technique_name or "N/A"}</td>
      </tr>
      <tr style="background:#f8f8f8;">
        <td style="padding:8px;font-weight:bold;">Tactic</td>
        <td style="padding:8px;">{alert.mitre_tactic or "N/A"}</td>
      </tr>
    </table>

    <h3 style="color:#555;margin-top:24px;">🔍 IOC Reputation</h3>
    <p style="font-size:14px;">{ioc_verdict}</p>

    <hr style="margin-top:30px;border:none;border-top:1px solid #eee;">
    <p style="font-size:12px;color:#999;">
      This is an automated alert generated by the Mini-SIEM Alerting System.
      Do not reply to this email.
    </p>
  </div>
</body>
</html>
"""


async def send_alert_email(alert: Alert) -> bool:
    """
    Sends an HTML email for the given alert.

    Returns True on success, False on failure.
    Does NOT raise — email failure must never crash the ingestion pipeline.
    """
    subject = (
        f"[{alert.severity.upper()}] SIEM Alert — {alert.event_type} "
        f"from {alert.source_ip}"
    )

    msg = MIMEMultipart("alternative")
    msg["Subject"] = subject
    msg["From"]    = SMTP_USER
    msg["To"]      = ", ".join(ALERT_RECIPIENTS)

    # Plain-text fallback
    plain = (
        f"SIEM Alert [{alert.severity}]\n"
        f"Event:       {alert.event_type}\n"
        f"Source IP:   {alert.source_ip}\n"
        f"Timestamp:   {alert.timestamp}\n"
        f"Description: {alert.description}\n"
        f"MITRE:       {alert.mitre_technique_id} — {alert.mitre_technique_name}\n"
        f"IOC:         {alert.ioc_reputation} ({alert.ioc_provider})\n"
    )
    msg.attach(MIMEText(plain, "plain"))
    msg.attach(MIMEText(_build_html_body(alert), "html"))

    try:
        await aiosmtplib.send(
            msg,
            hostname=SMTP_HOST,
            port=SMTP_PORT,
            username=SMTP_USER,
            password=SMTP_PASSWORD,
            start_tls=True,
        )
        logger.info(
            "Email alert sent for alert_id=%s severity=%s to %s",
            alert.id, alert.severity, ALERT_RECIPIENTS,
        )
        return True

    except Exception as exc:
        logger.error(
            "Failed to send email for alert_id=%s: %s", alert.id, exc
        )
        return False


async def notify(alert: Alert) -> bool:
    """
    Public entry-point for the notification layer.
    Only triggers for High / Critical alerts.
    """
    if alert.severity not in NOTIFY_SEVERITIES:
        logger.debug(
            "Skipping email for alert_id=%s (severity=%s below threshold)",
            alert.id, alert.severity,
        )
        return False

    return await send_alert_email(alert)
